function OvsT(XMatrix1, YMatrix1, DMatrix1, observable,ounits)
%CREATEFIGURE(XMATRIX1, YMATRIX1, DMATRIX1)
%  XMATRIX1:  errorbar x matrix data
%  YMATRIX1:  errorbar y matrix data
%  DMATRIX1:  errorbar delta matrix data

%  Auto-generated by MATLAB on 04-Jan-2017 15:59:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix1,DMatrix1,'MarkerSize',8,...
    'LineStyle','none',...
    'LineWidth',2);
set(errorbar1(1),'DisplayName','$\rho=0.3$');
set(errorbar1(2),'DisplayName','$\rho=0.8$');

% Create xlabel
xlabel('$T$ [$\varepsilon/k_B$]','FontSize',22,'Interpreter','latex');

% Create title
title(strcat(observable,' vs $T$'),'FontWeight','bold','FontSize',24,...
    'Interpreter','latex');

% Create ylabel
ylabel(strcat(observable,' [',ounits,']'),'FontSize',22,'Interpreter','latex');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','Interpreter','latex','FontSize',18);

