fimplicit( @(rho,T) rho.*T+rho.^2.*(crazyfitresult.x1.*T+crazyfitresult.x2.*sqrt(T)+crazyfitresult.x3+crazyfitresult.x4./T+crazyfitresult.x5./T.^2) ...
             + rho.^3.*(crazyfitresult.x6.*T+crazyfitresult.x7+crazyfitresult.x8./T+crazyfitresult.x9./T.^2) + rho.^4.*(crazyfitresult.x10.*T+crazyfitresult.x11+crazyfitresult.x12./T) ...
             + rho.^5.*(crazyfitresult.x13) + rho.^6.*(crazyfitresult.x14./T+crazyfitresult.x15./T.^2) + rho.^7.*(crazyfitresult.x16./T) ...
             + rho.^8.*(crazyfitresult.x17./T+crazyfitresult.x18./T.^2) + rho.^9.*(crazyfitresult.x19./T.^2) ...
             + ( rho.^3.*(crazyfitresult.x20./T.^2+crazyfitresult.x21./T.^3) ...
               + rho.^5.*(crazyfitresult.x22./T.^2+crazyfitresult.x23./T.^4)   + rho.^7.*(crazyfitresult.x24./T.^2+crazyfitresult.x25./T.^3) ...
               + rho.^9.*(crazyfitresult.x26./T.^2+crazyfitresult.x27./T.^4)   + rho.^11.*(crazyfitresult.x28./T.^2+crazyfitresult.x29./T.^3) ...
               + rho.^13.*(crazyfitresult.x30./T.^2+crazyfitresult.x31./T.^3+crazyfitresult.x32./T.^4) ) .* exp(-crazyfitresult.g.*rho.^2) ,...
           [0.05 1.0 0.60 1.5]);